"""
scripts/csv_to_videos_yaml.py
One-time script — convert a YouTube metadata CSV to data/videos.yaml.

Usage:
    python scripts/csv_to_videos_yaml.py <path/to/videos.csv>

The CSV must have at least these columns:
    video_id, title, description, upload_date, duration_sec,
    view_count, like_count, tags, url

Output: data/videos.yaml (sorted by publishedAt descending)
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def seconds_to_hms(secs: str) -> str:
    """Convert a duration in seconds to H:MM:SS or M:SS string."""
    try:
        total = int(float(secs))
    except (ValueError, TypeError):
        return ""
    h, remainder = divmod(total, 3600)
    m, s = divmod(remainder, 60)
    if h:
        return f"{h}:{m:02d}:{s:02d}"
    return f"{m}:{s:02d}"


def parse_tags(raw: str) -> list[str]:
    """Split a comma/pipe/space-separated tag string into a list."""
    if not raw:
        return []
    for sep in (",", "|", ";"):
        if sep in raw:
            return [t.strip().lower() for t in raw.split(sep) if t.strip()]
    return [t.strip().lower() for t in raw.split() if t.strip()]


def parse_int(value: str) -> int | None:
    try:
        return int(float(value))
    except (ValueError, TypeError):
        return None


# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------

def csv_to_videos(csv_path: Path) -> list[dict]:
    videos = []
    with csv_path.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            video_id = row.get("video_id", "").strip()
            if not video_id:
                continue

            # publishedAt: upload_date is already YYYY-MM-DD
            published_at = row.get("upload_date", "").strip()

            entry: dict = {
                "id": video_id,
                "title": row.get("title", "").strip(),
                "description": row.get("description", "").strip(),
                "publishedAt": published_at,
                "duration": seconds_to_hms(row.get("duration_sec", "")),
                "thumbnail": f"https://img.youtube.com/vi/{video_id}/maxresdefault.jpg",
                "playlist": row.get("playlist", "").strip() or "Videos",
                "tags": parse_tags(row.get("tags", "")),
            }

            view_count = parse_int(row.get("view_count", ""))
            if view_count is not None:
                entry["viewCount"] = view_count

            like_count = parse_int(row.get("like_count", ""))
            if like_count is not None:
                entry["likeCount"] = like_count

            videos.append(entry)

    # Sort newest first
    videos.sort(key=lambda v: v.get("publishedAt", ""), reverse=True)
    return videos


def save_yaml(path: Path, videos: list[dict]) -> None:
    header = (
        "# Videos data — generated by scripts/csv_to_videos_yaml.py\n"
        "# Sorted by publishedAt descending.\n\n"
    )

    # Use default_flow_style=False for block style; allow_unicode for special chars
    body = yaml.dump(
        videos,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
    )

    path.write_text(header + body, encoding="utf-8")
    print(f"Wrote {len(videos)} videos to {path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/csv_to_videos_yaml.py <path/to/videos.csv>")
        sys.exit(1)

    csv_path = Path(sys.argv[1]).resolve()
    if not csv_path.exists():
        print(f"File not found: {csv_path}")
        sys.exit(1)

    repo_root = Path(__file__).resolve().parent.parent
    out_path = repo_root / "data" / "videos.yaml"

    videos = csv_to_videos(csv_path)
    save_yaml(out_path, videos)
